### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by angeloashmore** [rom-rb/rom-rb.org#111]
Hello!

I know the design of the site is probably a low priority for ROM, but it's one way I could possibly contribute to the project. A welcoming landing page could entice more developers.

I created the attached designs in Sketch, but I can move forward into making this a full fledged site with Middleman.

Let me know if you would like me to move forward or hold off. Thanks!

<a href="https://cloud.githubusercontent.com/assets/8601064/11911251/35471be6-a5b3-11e5-88e4-af9663e5f732.png"><img src="https://cloud.githubusercontent.com/assets/8601064/11911251/35471be6-a5b3-11e5-88e4-af9663e5f732.png" height="200" /></a> <a href="https://cloud.githubusercontent.com/assets/8601064/11911252/39abeb4e-a5b3-11e5-9084-049eb3606760.png"><img src="https://cloud.githubusercontent.com/assets/8601064/11911252/39abeb4e-a5b3-11e5-9084-049eb3606760.png" height="200" /></a> <a href="https://cloud.githubusercontent.com/assets/8601064/11911253/3db0aef0-a5b3-11e5-9ef8-4de931991b6d.png"><img src="https://cloud.githubusercontent.com/assets/8601064/11911253/3db0aef0-a5b3-11e5-9ef8-4de931991b6d.png" height="200" /></a> <a href="https://cloud.githubusercontent.com/assets/8601064/11911339/557fc454-a5b7-11e5-90fa-375117f35e61.png"><img src="https://cloud.githubusercontent.com/assets/8601064/11911339/557fc454-a5b7-11e5-90fa-375117f35e61.png" height="200" /></a>

**Comment by solnic** [comment]
Angelo thank you so much for this! I like where this is going, please continue :)

**Comment by AMHOL** [comment]
Nice :heart:

**Comment by gotar** [comment]
+1

**Comment by kwando** [comment]
:+1:

**Comment by sagmor** [comment]
Awesome! :+1:

**Comment by angeloashmore** [comment]
Thanks! :smile:

Quick update: I'm working on this as I have time. You can see the progress at [angeloashmore/rom-rb.org](/angeloashmore/rom-rb.org).

I also mocked up the mobile pages:

<img width="200" src="https://cloud.githubusercontent.com/assets/8601064/12025964/281ec8d6-ad58-11e5-904f-771923e98b1c.png"> <img width="200" src="https://cloud.githubusercontent.com/assets/8601064/12025963/27f2bb2e-ad58-11e5-80c4-567343702551.png">

Please let me know if any of you have suggestions.

**Comment by solnic** [comment]
I really like it so far, love the purple accent :) BTW I replaced intro/guides/tutorials yesterday with pages informing that they are being rewritten, you could pull that into your fork and be able to easily update overall html structure etc. as there's way less content now.

**Comment by robinetmiller** [comment]
Are the colours for the syntax highlighting just pulled from the logo? It seems a little busy, and the yellow is difficult to parse.

**Comment by angeloashmore** [comment]
The syntax highlighting is base16-paraiso-dark. That's the demo of the colors I copy and pasted. Actual code snippets should be much less colorful. And if not, it's just a single CSS file change away. :smile:

**Comment by robinetmiller** [comment]
@angeloashmore To loop you in: the fork at https://github.com/TenjinInc/rom-rb.org is in the process of getting the new docs into markdown. I'm also merging the Introduction and Guides headers into one "Learn" subsection, and grouping together related things. 

We may want to collaborate with each other (even in the same repo) to avoid toe-trodding. I think it would be fantastic to get the new docs and the new design up together. :D

**Comment by solnic** [comment]
@robinetmiller @angeloashmore would it be possible to merge new-design-fork with new-docs-fork some time next week? I'll be working on docs full-time throughout the week with the goal to publish updated website on Friday :)

**Comment by angeloashmore** [comment]
@solnic @robinetmiller Sorry for the delay. I returned to school this week and am still adjusting to the different schedule. I'm still working on this when I am able to.

The landing page and base styles have been completed. I'm starting to style the sub-pages (guides, blog, etc.). I'll post updates as they are completed.

I saw the new docs were published. Looks good! If it's okay with you, I'll keep the new design a separate repo for now since it is still a WIP. Once it's complete, we can look into merging.

![screen shot 2016-01-15 at 7 08 57 pm](https://cloud.githubusercontent.com/assets/8601064/12370618/a454738a-bbbb-11e5-8aab-1ee01232edbc.png)

**Comment by angeloashmore** [comment]
![screen shot 2016-01-15 at 7 44 52 pm](https://cloud.githubusercontent.com/assets/8601064/12370740/7faf09aa-bbc0-11e5-9c53-b3335de57836.png)

**Comment by angeloashmore** [comment]
Preview at:
- Landing pagehttp://crazy-authority.surge.sh
- Sub-page: http://crazy-authority.surge.sh/guide

**Comment by solnic** [comment]
Angelo, I love it, thank you! Let me know if you need help with anything to
finalize this :)

**Comment by angeloashmore** [comment]
@solnic @robinetmiller Are the doc files in master the latest? Finishing up a few things with the design and want to ensure compatibility.

**Comment by solnic** [comment]
@angeloashmore fantastic! yes, current master is what we have published at rom-rb.org

**Comment by angeloashmore** [comment]
Cool, I should have it finalized today for you to check out. As always, I'm open to any suggestions. :smile:

**Comment by solnic** [comment]
Amazing! Looking forward to it <3

**Comment by angeloashmore** [comment]
Hosted preview: https://crazy-authority.surge.sh
Repository: https://github.com/angeloashmore/rom-rb.org

Everything should be working, but let me know if something appears broken.

**Comment by solnic** [comment]
@angeloashmore thanks, this looks gorgeous. Could you maybe send a pull request?

**Comment by angeloashmore** [comment]
@solnic PR sent: https://github.com/rom-rb/rom-rb.org/pull/117
