### ISSUE TITLE
Restore "Edit this article on GitHub" links

### ISSUE THREAD

**Issue by muescha** [rom-rb/rom-rb.org#120]
the link "Edit this article on GitHub" is broken because the repo is moved from https://github.com/tenjininc/rom-rb.org/ to https://github.com/rom-rb/rom-rb.org/

**Comment by CucumisSativus** [comment]
Looks like there's no such link on the new master. @solnic would you like to have such a link on the new page?

**Comment by muescha** [comment]
i see the edit link here at this page: http://rom-rb.org/learn/

**Comment by vaz** [comment]
Here's where it seems to be generated: https://github.com/rom-rb/rom-rb.org/blob/guides/config.rb#L116-L122

It's updated in that file, but still not on the site. Does it just need to be redeployed?

**Comment by solnic** [comment]
we'll update the website later this month so this will work again, sorry about that

**Comment by solnic** [comment]
I didn't manage to restore these links, help-wanted ;)

**Comment by muescha** [comment]
the "Edit on GIthub" Buttons still not work and link to a 404

example:
http://rom-rb.org/4.0/learn/introduction/

link to 404:
https://github.com/rom-rb/rom-rb.org/blob/master/source/4.0/learn/introduction/index.html.slim
