### ISSUE TITLE
Add automatic generator for sidebar nav in Learn

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-rb.org#137]

**Comment by angeloashmore** [comment]
This should be pretty easy to implement, but a few changes would be necessary:

- [ ] **Add ordered number prefixes to filenames**
  This will allow an explicit ordering of guides. For example:
  - `learn/introduction/01__philosophy.html.md`
  - `learn/introduction/02__why.html.md`
  - `learn/introduction/03__overview.html.md`
  - `learn/introduction/04__active-record.html.md`
  - `learn/introduction/index.html.md`

- [ ] **Standardize frontmatter**
  `title` and `chapter` frontmatter items aren't present in all guides. Those that do have it are inconsistent in their use. Maybe change it to `section` (e.g. Introduction, Core, …) and `title` (e.g. Overview, Schemas, …)?

If this sound okay, I'll make the changes.

**Comment by solnic** [comment]
I did something like that in [dry-rb.org](https://github.com/dry-rb/dry-rb.org) but used a different strategy - every main section page defines `sections` in its frontmatter with a list of sub-sections, then we use this meta-data to generate links in correct order. WDYT?
