### ISSUE TITLE
Add status page

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-rb.org#14]
ROM consists of the core gem and adapters and it would be very helpful to show everything on one page along with version numbers and some information about stability of individual pieces.

For instance rom and rom-sql 1.0.0 will be released soon but rom-mongo will remain < 1.0.0 for a while. The same will happen with other adapters.

**Comment by elskwid** [comment]
Status page added in d435872a04953e82.

URL: http://rom-rb.org/status/

![rom ruby object mapper - status 2015-01-26 16-40-46](https://cloud.githubusercontent.com/assets/9002/5911401/1970c44c-a57a-11e4-8fe7-a52f1436472b.png)

**Comment by splattael** [comment]
:metal:

**Comment by solnic** [comment]
oh wow I did not see that coming :) awesome!

**Comment by aflatter** [comment]
:+1: nice
