### ISSUE TITLE
Gateway link in leard advance topis is broken

### ISSUE THREAD

**Issue by alexandru-calinoiu** [rom-rb/rom-rb.org#169]
Any thoughts where this https://github.com/rom-rb/rom-rb.org/blob/master/docs/learn/advanced/flat-style-setup/index.html#L84 should point to.

**Comment by solnic** [comment]
Oh, it should point to `/learn/glossary#gateway` and we also need to actually add anchors to this page.

**Comment by alexandru-calinoiu** [comment]
Fixed it here https://github.com/rom-rb/rom-rb.org/pull/171
