### ISSUE TITLE
Wrong version on 4.0 documentation

### ISSUE THREAD

**Issue by cpgo** [rom-rb/rom-rb.org#201]
On [this file](https://github.com/rom-rb/rom-rb.org/blob/master/source/4.0/learn/getting-started/index.html.md) it says `Compatible with rom 3.0`, is it right or it was supposed to be `rom 4.0`?

**Comment by flash-gordon** [comment]
Not quite right yet, atm only `rom-sql` is compatible with rom `4.0`, support for more adapters is coming soon.

**Comment by cpgo** [comment]
But should we leave the text as it is?

**Comment by solnic** [comment]
Yeah this has to be updated. I'd probably just add another table for rom 4.0 (and only rom-sql would be there for now). Sounds good?

**Comment by cpgo** [comment]
Sounds good to me.
Will you do It or wanna me to open a PR?

**Comment by solnic** [comment]
PRs are always welcome
