### ISSUE TITLE
Provide a full script as reference

### ISSUE THREAD

**Issue by Kjarrigan** [rom-rb/rom-rb.org#207]
Hey guys,

every time I read that there is a new release of rom, I try to check it out as alternative to ActiveRecord because I really want one. I tried like 3 times but I just can't work out an working script to connect to an existing postgresql database to just fetch some records. I have to click to dozens of topics at rom-rb.org with small snippets showing me different options but there is no whole script from require to a working query where I can just see a "real life" scenario to get how all the different parts connect. I have adapter and containers and relations and repositories and changesets and ... I hope you get the point.

So if anyone has some code to use as reference please share it with me and maybe think about providing a fullscript http://rom-rb.org. At least for me a piece of code is so much more informative then hundreds of pages of documentation (I'll look there when I want to dive deeper in my specific use-cases).

Thanks,
Kjarrigan

**Comment by abrthel** [comment]
Could you can provide a quick db schema for me that illustrates a scenario you need documented?

Also are we talking just a simple single file script with all of the components or are you looking for a full fledged example with a particular framework?

**Comment by solnic** [comment]
Just updated [quick start guide](http://rom-rb.org/4.0/guides/sql-quick-start/connecting-to-existing-database/) which explains exactly what you asked. Is this OK?

**Comment by Kjarrigan** [comment]
Hi @abrthel 

at the moment I'm most interested in the usage without a particular framework. I have quite a lot of scripts / cli-tools and even a few gui's (with fxruby) where I need to fetch some records from the database, do some magic and sometime update or delete some records.

Following you find a really simplified script with some common operations I do with AR and the SQL for the database-part.

```ruby
require 'active_record'

module Foo
  class Group < ActiveRecord::Base
    has_one :some_ref_table
    has_many :bars
  end

  class SomeRefTable < ActiveRecord::Base
    belongs_to :group
  end

  class Bar < ActiveRecord::Base
    belongs_to :group
  end

  def self.connect_db(params={})
    default = {
      adapter: 'postgresql',
      # host: 'localhost',
      database: 'rom_example_01',
      # user: 'dummy',
      # password: 'ymmud',
      schema_search_path: 'dummy'
    }
    ActiveRecord::Base.establish_connection(default.merge(params))
  end
end

def do_stuff(group_name, nr_bars)
  group = Foo::Group.find_or_create_by(name: group_name)

  Foo::Group.transaction do
    group.create_some_ref_table(name: group_name.reverse)

    # Direct Query because its faster
    Foo::Bar.connection.exec_query("INSERT INTO dummy.bars (group_id, field01) SELECT #{group.id}, x.id FROM generate_series(1,#{nr_bars}) AS x(id);")

    # find_each due to performance issues with large values for nr_bars
    group.bars.find_each do |bar|
      bar.field02 = rand(100)
      bar.save
    end
  end
end

Foo.connect_db
ActiveRecord::Base.logger = Logger.new(STDERR)

do_stuff(ARGV[0], ARGV[1])
```

```sql
CREATE SCHEMA dummy;

CREATE TABLE dummy.groups (
  id SERIAL PRIMARY KEY,
  name VARCHAR
);

CREATE TABLE dummy.some_ref_tables (
  id SERIAL PRIMARY KEY,
  group_id INTEGER,
  name VARCHAR
);

CREATE TABLE dummy.bars (
  id SERIAL PRIMARY KEY,
  group_id INTEGER,
  field01 INTEGER,
  field02 VARCHAR
);
```

**Comment by abrthel** [comment]
@Kjarrigan, hey thanks for the info. I'm a bit busy today but leave this with me and I'll try and get a 'Putting it all together' guide created. Does the guide solnic linked to help or is it a matter of needed to see more features working together at once?

**Comment by Kjarrigan** [comment]
Hey @abrthel somehow missed @solnic link. But that looks rather promising as a start but if you could spare some time to get a quick 'Putting it all together' guide up it would be awesome. Meanwhile I'll see if I can convert some of my scripts by the direction @solnic provided. If I get anything up and running I'll share it with you so there mightbe a showcase for others with "from AR to ROM"-examples.

**Comment by v-kolesnikov** [comment]
Hi, @Kjarrigan

This implementation quite dirty, but it's working!

```ruby
#!/usr/bin/env ruby

# Create database
# system "psql -c 'create database dummy_db;' -U postgres"
# system 'psql dummy_db -U postgres < db.sql'

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'pg'
  gem 'rom', '~> 4.0.0'
  gem 'rom-sql', '~> 2.0'

  gem 'pry-byebug'
end

require 'sequel'
require 'rom'
require 'rom-sql'

set_search_path = ->(conn) { conn.execute('SET SEARCH_PATH TO dummy') }

rom = ROM.container(:sql, 'postgres://postgres@0.0.0.0/dummy_db',
                    after_connect: set_search_path) do |config|
  config.relation(:groups) do
    schema(infer: true) do
    end
  end

  config.relation(:some_ref_tables) do
    schema(infer: true) do
      associations do
        belongs_to :group
      end
    end
  end

  config.relation(:bars) do
    schema(infer: true) do
      associations do
        belongs_to :group
      end
    end
  end
end

# You can use awesome Dry::Container instead!
CONTAINER = {
  rom: rom,
  conn: rom.gateways[:default].connection
}.freeze

CONTAINER[:conn].logger = Logger.new(STDERR)

module Foo
  module Persistence
    module Repostitories
      class Groups < ROM::Repository::Root[:groups]
        commands :create, update: :by_pk

        def by_name(name)
          groups.where(name: name).one
        end
      end

      class SomeRefTables < ROM::Repository::Root[:some_ref_tables]
        commands :create, update: :by_pk
      end

      class Bars < ROM::Repository::Root[:bars]
        commands :create, update: :by_pk

        def by_group_id(group_id)
          bars.where(group_id: group_id)
        end
      end
    end
  end

  class SomeServise
    def call(group_name, nr_bars)
      # With Dry::Container and Dry::AutoInject all you need is:
      # include Foo::Import[
      #   'persistence.repositories.bars',
      #   'persistence.repositories.groups',
      #   'persistence.repositories.some_ref_tables'
      # ]
      groups = Foo::Persistence::Repostitories::Groups.new(CONTAINER[:rom])
      some_ref_tables = Foo::Persistence::Repostitories::SomeRefTables.new(CONTAINER[:rom])
      bars = Foo::Persistence::Repostitories::Bars.new(CONTAINER[:rom])

      group = groups.by_name(group_name)
      group ||= groups.create(name: group_name)

      connection = CONTAINER[:rom].gateways[:default].connection

      connection.transaction do
        some_ref_tables.create(group_id: group.id, name: group_name.reverse)

        # You can define it as a command
        connection.execute(
          "INSERT INTO dummy.bars (group_id, field01) " \
          "SELECT #{group.id}, x.id " \
          "FROM generate_series(1,#{nr_bars}) AS x(id);"
        )

        bars.by_group_id(group.id).each do |bar|
          bars.update(bar.id, field02: rand(100))
          # Or equal:
          # bars.by_pk(bar.id).changeset(:update, field02: rand(100)).commit
        end
      end
    end
  end
end

puts Foo::SomeServise.new.('some_group', 5) # Use .map(&:to_h) to see structs
```

If you going to make real application with ROM pay attention to https://github.com/dry-rb/dry-web-roda project which uses ROM widely.

**Comment by Kjarrigan** [comment]
Hi @v-kolesnikov,

thats actually really helpfull and should be listed in the [guides](http://rom-rb.org/4.0/guides/) section as example for a more realistic reference as you usually have a couple of tables which are somewhat dependent instead of just connecting to a single table.

**Tanks a lot** :+1: There are quite some snippets I just couldn't figure out myself (e.g. how to set the schema_search path with the _after_connect_ hook) and there are still some things I personally don't like (e.g. the _String-URI_ to connect to a database) but other than that I'm good to go to finally dive a bit deeper in the rom and validate if this is an feasable replacement to AR for my particular usecases.

**PS:** Please think about adding more examples / guides. In most of your learning topics you compare to AR, so I think it would be cool to have here and there a direct comparison of "How to do thingy A in AR and how to do it in Rom"

**PPS:** Congratulations to @solnic as [final nominee for the ruby prize 2017](http://www.ruby.or.jp/ja/news/20172026)

**Comment by solnic** [comment]
This script can be written in a simpler way, ie without repositories, and you can levarage schema features a bit better too. I'll get back to you with a sample script showing how I'd do it :)

> PPS: Congratulations to @solnic as final nominee for the ruby prize 2017

Thanks man, I'm literally waiting for my flight to Japan right now :D

**Comment by solnic** [comment]
FYI sql docs have been updated with a lot of details about connection options http://rom-rb.org/4.0/learn/sql/
