### ISSUE TITLE
Document advanced connection options

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-rb.org#209]
refs #207

**Comment by abrthel** [comment]
I'll take this one, I wanted to update the SQL adapter index page anyways and that seems like a good place for connection options.

**Comment by solnic** [comment]
@abrthel sounds great! TY :)

**Comment by abrthel** [comment]
Haven't forgotten about this one, just didn't get as far as I'd hoped. You can checkout my [current progress](https://github.com/abrthel/rom-rb.org/blob/2502739248c889568d3a9d7a5fa04b666a8015f9/source/4.0/learn/sql/index.html.md) but it should be completed in the next couple days or worse case next weekend.
