### ISSUE TITLE
Feedback on ROM - Overview

### ISSUE THREAD

**Issue by apohllo** [rom-rb/rom-rb.org#216]
I think that an image clarifying the relations between the concepts would make the whole picture more understandable.

**Comment by abrthel** [comment]
https://github.com/rom-rb/rom-rb.org/pull/212/files

Does this document help?

**Comment by solnic** [comment]
Coincidentally, we just ported this section to `Getting Started / Core Concepts`, please check it out http://rom-rb.org/4.0/learn/getting-started/core-concepts/ (it's got the image :))

**Comment by apohllo** [comment]
Wow, great! :1st_place_medal:
