### ISSUE TITLE
Rewrite "ActiveRecord and ROM"

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-rb.org#230]
It should be now feasible to rewrite this section and turn it into a side-by-side comparison.

**Comment by abrthel** [comment]
I was thinkin the exact same thing. Plus it its on my list.

**Comment by solnic** [comment]
Cool! We can work on this together.

**Comment by abrthel** [comment]
I would like that. 
I'll distill as much of your moscow talk into the doc first, then post it so you can revise and add. Sound ok?
https://speakerdeck.com/solnic/rom-rb-4-dot-0-moscow-railsclub-2017
