### ISSUE TITLE
Feedback on ROM - Rails Setup

### ISSUE THREAD

**Issue by xero88** [rom-rb/rom-rb.org#252]
I give up to install rom-rb on my project.
This documentation need a step to step setup into a rails project with a real database (like postgres).
This is frustrating, because rom-rb seems to be useful. But I can try 2-3 days to setup the gem.
Maybe I'm too noob to setup this gem.

**Comment by solnic** [comment]
What problems did you have?

**Comment by xero88** [comment]
`bin/rails console`
`/var/lib/gems/2.4.0/gems/sequel-5.6.0/lib/sequel/database/connecting.rb:17:in `adapter_class': undefined method `to_sym' for nil:NilClass`

Maybe I can close this post, because more generally I have the same issues than https://github.com/rom-rb/rom-rb.org/issues/249

The lack of get-started with rails

**Comment by solnic** [comment]
Fair enough. Maybe somebody will write a nice step-by-step tutorial for Rails.

**Comment by cflipse** [comment]
I just yesterday released an update to rom-rails that fixes a couple of bootstrapping problems, and adds a `rom:install` generator that will probably help.

I'll also do some work this weekend on a bootstrapping guide for rom-rails.  There _are_ still a number of sharp edges, however.

**Comment by felideon** [comment]
For the record. I was getting the same error as above. Fixed by defining the fully qualified database URL, e.g. `postgres://host/db`.
