### ISSUE TITLE
Rom website has Content Security Policy errors in iframe

### ISSUE THREAD

**Issue by skade** [rom-rb/rom-rb.org#265]
Navigate to: http://rom-rb.org/api/rom/

And click the "mapper" link in the readme.

Because rom-rb.org is HTTP and the link links to GitHub using HTTPS, there will be an error.

This should be fixed by serving rom-rb.org over https, which GH should provide now through let's encrypt.

**Comment by madis** [comment]
Not just that but when I visit the url https://rom-rb.org/api/rom/ it tries to load iframe from http://localhost:4000/docs/rom

![screen shot 2018-08-28 at 11 13 57](https://user-images.githubusercontent.com/674621/44709935-91fdd700-aab3-11e8-90d7-8e63270c2829.png)

**Comment by solnic** [comment]
I'm sorry but this is still broken, because we serve API docs from api.rom-rb.org, so browsers block this iframe by default. I need to figure out how to solve this.

**Comment by solnic** [comment]
closing this because we no longer embed API docs in an iframe
