### ISSUE TITLE
Missing docs for pagination plugin

### ISSUE THREAD

**Issue by thomas** [rom-rb/rom-rb.org#270]
Can't find any documentation about the pagination plugin, how to enable it, etc.

**Comment by solnic** [comment]
Thanks, we should definitely cover that in SQL docs. For the time being, all you need is this:

``` ruby
class YourRel < ROM::Relation[:sql]
  use :pagination
  per_page 20 # that's optional, defaults to 10
end
```

Instance API is documented [here](https://api.rom-rb.org/rom-sql/ROM/SQL/Plugin/Pagination.html#per_page-instance_method).

**Comment by solnic** [comment]
Closing because as it was reported as https://github.com/rom-rb/rom-sql/issues/359
