### ISSUE TITLE
The "Edit on Github" link on rom-rb.org quick-setup points to the old rom-rb/rom-core github repository.

### ISSUE THREAD

**Issue by salticus** [rom-rb/rom-rb.org#325]
The "Edit on Github" link on [rom-rb.org quick-setup](https://rom-rb.org/learn/core/5.2/quick-setup/) points to the old [rom-rb/rom-core](https://github.com/rom-rb/rom-core/blob/release-5.2/docsite/source/quick-setup.html.md) github repository. 

- [ ] Change link to point to ~~this~~ the correct repository.
- [ ] Check other links on the site for the same issue.
- [ ] Ask about auto-link checking functionality (mentioned elsewhere; I have lost the location.)
- [ ] Ask about relationship of documentation policy with respect to individual gem development and this site.
       Following [4 kinds of documentation](https://www.writethedocs.org/videos/eu/2017/the-four-kinds-of-documentation-and-why-you-need-to-understand-what-they-are-daniele-procida/) guessing that the setup is for Gems to have API docs, and that the other three kinds are found here: tutorials, guides, and design? Or simply that all documentation is aggregated here?
       This belongs with this group of tasks because the existence of similar documentation in rom-rb/core caused some initial confusion. If documentation is split across multiple repositories, then aggregated here, adding explanations and/or links in each repository (in a sane way) will help other newcomers (of course this may already be the case; I have not read the documentation source carefully.)

# Context
I had trouble following https://rom-rb.org/learn/core/5.2/quick-setup/ (TODO: separate issue.)
The "Edit on Github" link points to the non-existent ~~https://github.com/rom-rb/rom/blob/master/docsite/core/source/quick-setup.html.md~~ https://github.com/rom-rb/rom-core/blob/release-5.2/docsite/source/quick-setup.html.md

It seems the link should instead be
https://github.com/rom-rb/rom/blob/release-5.2/core/docsite/source/quick-setup.html.md

Looking through the [rom-rb](https://github.com/rom-rb/) organization, I found what [appeared to be](https://github.com/rom-rb/rom/tree/master/docsite/core/source) the corresponding documentation in the rom repository.
After asking on [zulipchat](https://rom-rb.zulipchat.com/#narrow/stream/191800-general/topic/Documentation.20(rom-rb.2Eorg)) I was directed to submit the issue to this repository instead.

**Comment by solnic** [comment]
Looks like it works well now. Thanks for helping with this! ❤️
