### ISSUE TITLE
"Why ROM" section needs a better explanation

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-rb.org#33]
Based on the feedback on [reddit thread](http://www.reddit.com/r/ruby/comments/2r0as2/ruby_object_mapper_050_released_along_with_a_big/cnbixdu)

**Comment by abrthel** [comment]
If this can wait possibly a few weeks, I can take this one too. I have this faint idea of merging the Philosophy and Why ROM pages which should flow nicely into the new Core Concepts page (assuming it gets accepted).

**Comment by solnic** [comment]
@abrthel sure no rush at all :) I like the idea of merging these 2 pages btw. I actually think there's too much text, and too little "essence", if you know what I mean. It should be possible to explain why rom might be a better choice, with less words 😆

**Comment by abrthel** [comment]
I'm starting on this now, so I should have something to look at by Monday.
