### ISSUE TITLE
Add a page about contributing?

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-rb.org#43]
How about adding a dedicated page with all the information about how to become a contributor? There's a lot of knowledge common for all rom-* projects so it feels wrong to duplicate it in CONTRIBUTING file in each repo.

This page could cover things like:

* Code style guidelines (probably boils down to "run rubocop" to get feedback however I'm worried that people might be pushed by rubocop to do silly refactorings like breaking down a method into 2 because some artificial limit is exceeded etc.)
* Basic design principles (avoid mutation, how OO is done in ROM, functional tidbits etc.)
* Support interface (Equalizer, ClassMacros, Options etc.)
* Git guidelines (esp regarding squashing, when to, when not to, what to write in commit messages)
* How to get help and support from core contributors
* How to find what to work on (it would be freaking cool to dynamically list issues tagged "help-wanted" there!)

**Comment by maetl** [comment]
FYI, I’ve started working on this.
