### ISSUE TITLE
Add AR | ROM side-by-side comparison

### ISSUE THREAD

**Issue by elskwid** [rom-rb/rom-rb.org#44]
I would like to add a section to the site where you can compare how you do things in ActiveRecord and what the corresponding code looks like in ROM.

In AR you would do this: [code]
In ROM it would look like this: [code]

**Comment by ginjo** [comment]
I would love to see DM added to this comparison... a side-by-side-by-side.

**Comment by solnic** [comment]
I'm having second thoughts about this. Feels like comparing apples to oranges. I think we should discuss it before publishing any comparisons. Since ROM is so fundamentally different from AR and DM it may give a wrong impression in many cases that it's "too complex".

**Comment by solnic** [comment]
Gonna close this one since eventually I think it doesn't make much sense. AR is *huge* and comparing it won't provide much value. Feel free to re-open if you don't agree.
