### ISSUE TITLE
Add "edge" version of docs and tutorials to the site

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-rb.org#50]
It would be great to have a way of updating docs and tutorials during development so that it doesn't end up as a last big and overwhelming task just before a release.

**Comment by maetl** [comment]
I think this can be partially solved by some changes to the navigation/content structure of the docs. As well as the normal distinction between tutorials, guides and references, we should consider an additional layer of distinction based on rate of change.

I have some ideas around how to do this—let’s keep the discussion going, and look at addressing this more thoroughly once the Rails tutorial changes are merged in.

**Comment by solnic** [comment]
Sounds good. There are also some implementation details of the website itself that are suboptimal (too much duplication). I almost wonder if we should build an app for the website as sticking to middleman might not be feasible.

**Comment by solnic** [comment]
finally done 😅
