### ISSUE TITLE
Feedback and comments collected by going through the guides

### ISSUE THREAD

**Issue by stravid** [rom-rb/rom-rb.org#75]
**Setup page**
I initially thought the `:sql` in `ROM::Relation[:sql]` refers to what gateway the relation should use. The `gateway` method a few paragraphs down suggests that is not the case and I have to find out later.

**Relations page**
I really like the glossary.

Due to my lack of Ruby skills this line `name_list = -> users { users.map { |user| user[:name] }` took some time to process and in addition I think there is a `}` missing.

Combining relations sounds like a really important topic but the example line `users.by_name('Jane').combine(tasks.for_users)` is magic to me and I can only imagine what happens behind the scene or what the output looks like. In my mind I always tried to imagine how this combining looks like for example as SQL query. I'm not sure if I need to know this but currently it bothers me a little that I have this feeling of magic and not understanding.

Loading relations is also a little confusing. I think I understand it but I'm not sure what I would use in practice for what etc.

**Mappers page**
`attribute :role # no coersion needed, this work is done by the mapper` should this be `:roles` according to the previous examples?

**Commands page**
Why is `.with` used when combining commands, I think I see it the first time and wonder why this line
`command = create_user.with(new_user) >> create_tasks.with(new_tasks)` cannot be this `command = create_user.call(new_user) >> create_tasks.call(new_tasks)`?

**Comment by nepalez** [comment]
@stravid thanks, David. Will change this in a mappers

**Comment by lengarvey** [comment]
## SQL Adapter guide

> The only additions are `associates` plugin which can automatically set foreign-key value when using command composition or command graph and `transaction` interface.

I don't understand what this is meant to mean. 

//cc @solnic

**Comment by maetl** [comment]
@lengarvey See #85
