### ISSUE TITLE
Error in example code?

### ISSUE THREAD

**Issue by robinetmiller** [rom-rb/rom-rb.org#81]
First day ROMming. Reading the documentation, starting with the Setup guide ( http://rom-rb.org/guides/basics/setup/ ).

Is the code under "Defining Components" correct?
```ruby
class Users < ROM::Memory[:memory]
end
```

Should that be `ROM::Relation` not `ROM::Memory`? `Memory` doesn't run for me, but `Relation` does (and makes more sense).

**Comment by AMHOL** [comment]
Hi @robinetmiller, yep, looks like that should be `ROM::Relation[:memory]`
