### ISSUE TITLE
rom 0.9.0.rc1: Setup example raises ROM::Registry::ElementNotFoundError

### ISSUE THREAD

**Issue by jaredbeck** [rom-rb/rom-rb.org#87]
The last example on http://rom-rb.org/guides/basics/setup/ raises `ROM::Registry::ElementNotFoundError`.

To reproduce:

```
# Gemfile
ruby '2.2.2'
source 'https://rubygems.org'
gem 'rom', '0.9.0.rc1'
gem 'rom-rails', '0.5.0.rc1'

# setup.rb
require 'rom'
ROM.setup(:memory)

class Users < ROM::Relation[:memory]
end

class CreateUser < ROM::Commands::Create[:memory]
  relation :users
  register_as :create
  result :one
end

ROM.finalize

rom = ROM.env

# access users relation
rom.relation(:users)
```

Run with `bundle exec ruby setup.rb`.

```
/Users/jared/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rom-support-0.1.0/lib/rom/support/registry.rb:30:in `block in []': :users doesn't exist in ROM::RelationRegistry registry (ROM::Registry::ElementNotFoundError)
	from /Users/jared/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rom-support-0.1.0/lib/rom/support/registry.rb:30:in `fetch'
	from /Users/jared/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rom-support-0.1.0/lib/rom/support/registry.rb:30:in `[]'
	from /Users/jared/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rom-0.9.0.rc1/lib/rom/container.rb:71:in `relation'
	from setup.rb:18:in `<main>'
```

I don't know if this is a docs issue or a regression in rom 0.9.0.rc1, but I'm being optimistic and reporting it here.

**Comment by AMHOL** [comment]
@jaredbeck that needs updating, automatic registration has been moved to a plugin to allow for multi-env support, you will need to call `ROM.use :auto_registration` somewhere before `ROM` components (relations, commands and mappers) are loaded to match the old behaviour.

**Comment by solnic** [comment]
I'm sorry for this. Guides are not up to date with 0.9.0 yet.

**Comment by jaredbeck** [comment]
What is the recommended alternative to `ROM.use :auto_registration`? Is there is an API for manually registering relations, mappers, etc.

**Comment by AMHOL** [comment]
@jaredbeck the alternative is to create an environment and register components manually:

```ruby
rom = ROM::Environment.new
rom.setup(:memory)

class Users < ROM::Relation[:memory]; dataset :users; end
class UserMapper < ROM::Mapper
  relation :users
  register_as :entity
  model Struct.new('User', :id, :name)
end
class CreateUser < ROM::Commands::Create[:memory]
  register_as :create
  relation :users
  result :one
end

rom.register_relation(Users)
rom.register_mapper(UserMapper)
rom.register_command(CreateUser)

container = rom.finalize.env
```

However, you can still create a `ROM::Environment` and use the `:auto_registration` plugin, it also now accepts an `:if` proc to determine whether to register the class or not:

```ruby
rom = ROM::Environment.new
rom.setup(:memory)
# Register everything that gets defined
rom.use :auto_registration
# Only register classes in the "Web" namespace
rom.use :auto_registration, if: ->(item) { item.to_s[/(.*)(?=::)/] == 'Web' }
# ...
```

**Comment by AMHOL** [comment]
Also worth noting that the regex in the example returns the full namespace so in most cases you're probably just better off using `String#start_with?`

```ruby
'ROM::Memory::Relations::Users'.to_s[/(.*)(?=::)/]
# => "ROM::Memory::Relations"
```

**Comment by jaredbeck** [comment]
Closing via https://github.com/rom-rb/rom-rb.org/pull/88

**Comment by jaredbeck** [comment]
> the [recommendation] is to create an environment and register components manually

I like this recommendation, btw. It seems like a situation where explicit is better than implicit. I'm guessing you were using `Class.inherited` before, and that's a bit too magical for my taste; ruby is the only language I know of that has that callback.  Also, I'd imagine removing the callback just makes the framework simpler.

**Comment by solnic** [comment]
@jaredbeck it's a convenient feature that we managed to work properly inside framework-integration gems; having said that, it was a really really bad approach for cases where you want to use ROM in a shared piece of code which is meant to provide rom components (ie a library that encapsulates data access to some API using `rom-http`, ships with its own relations and commands). For this reason the global set had to be removed and made optional, but @AMHOL managed to come up with the auto_registration plugin which optionally adds the original auto-registration behavior using `inherited` hook.

Personally I like explicitness too, using those hooks is fragile and tricky but so far it's been working correctly for me so I still use it. I'll be experimenting with a simpler approach in my custom web stack soon, so I'll report how it goes :)
